config/routes.rb
LtiOffice365::Engine.routes.draw do
  match '/launch', to: 'launch#show', via: [:get, :post]
  get '/configure', to: 'configure#show'
  get '/files(/:id)', to: 'files#index', as: 'directory'
  get '/files/download/:id', to: 'files#download', as: 'download'
  get '/auth/:provider/callback', to: 'sessions#create'
  match '/logout', to: 'sessions#destroy', via: [:get, :delete]
end

app/models/lti_office365/user.rb
module LtiOffice365
  class User < ActiveRecord::Base
    class << self
      def from_omniauth(auth_hash)
        user = find_or_create_by(uid: auth_hash['uid'])
        user.name = auth_hash['info']['name']
        user.email = auth_hash['info']['email']
        user.token = auth_hash['credentials']['token']
        user.refresh_token = auth_hash['credentials']['refresh_token']
        user.save!
        user
      end
    end
  end
end

app/controllers/lti_office365/application_controller.rb
module LtiOffice365
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    protected

    def allow_iframe
      response.headers['X-Frame-Options'] = 'ALLOWALL'
    end

    private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
    helper_method :current_user
  end
end

app/controllers/lti_office365/configure_controller.rb
require_dependency 'lti_office365/application_controller'

module LtiOffice365
  class ConfigureController < ApplicationController
    def show
      respond_to do |format|
        format.xml do
          render xml: Rails.application.config.office365[:launch].to_xml
        end
      end
    end
  end
end

app/controllers/lti_office365/files_controller.rb
require_dependency 'lti_office365/application_controller'

module LtiOffice365
  class FilesController < ApplicationController
    before_action :allow_iframe

    # Lists User's file at a `diectory_id`, otherwise root directory
    def index
      @directory = office365_client.get(Office365.directory(params[:id]))
    end

    # Creates OneDrive share link
    def download
      @share_link = office365_onedrive_service.create_share_link(params[:id])
      respond_to do |format|
        format.html { redirect_to @share_link }
        format.json { render json: { url: @share_link } }
      end
    end

    protected

    def office365_client
      @office365_client ||= Office365::Client.new(current_user)
    end

    def office365_onedrive_service
      @office365_onedrive_service ||= Office365::OnedriveService.new(current_user)
    end
  end
end

app/controllers/lti_office365/launch_controller.rb
require_dependency 'lti_office365/application_controller'

module LtiOffice365
  class LaunchController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :allow_iframe, :post_params

    def show
    end

    protected

    def post_params
      req = request.request_parameters.merge(request.query_parameters)
      lti_message = IMS::LTI::Models::Messages::Message.generate(req)
      lti_message.launch_url = request.url
      params.merge!(message: lti_message.post_params)
    end
  end
end

app/controllers/lti_office365/sessions_controller.rb
require_dependency 'lti_office365/application_controller'

module LtiOffice365
  class SessionsController < ApplicationController
    def create
      @user = User.from_omniauth(auth_hash)
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
      redirect_to launch_path
    rescue
      flash[:warning] = 'Could not authenticate'
      redirect_to launch_path
    end

    def destroy
      if current_user
        session.delete(:user_id)
        flash[:success] = 'Successfully logged out'
      end
      redirect_to launch_path
    end

    protected

    def auth_hash
      request.env['omniauth.auth']
    end
  end
end

app/helpers/lti_office365/application_helper.rb
module LtiOffice365
  module ApplicationHelper
  end
end

app/helpers/lti_office365/configure_helper.rb
module LtiOffice365
  module ConfigureHelper
  end
end

app/helpers/lti_office365/files_helper.rb
module LtiOffice365
  module FilesHelper
  end
end

app/helpers/lti_office365/launch_helper.rb
module LtiOffice365
  module LaunchHelper
  end
end

app/helpers/lti_office365/sessions_helper.rb
module LtiOffice365
  module SessionsHelper
  end
end

app/views/layouts/lti_office365/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LtiOffice365</title>
  <%= stylesheet_link_tag    'lti_office365/application', media: 'all' %>
  <%= javascript_include_tag 'lti_office365/application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<% if current_user %>
  <%= current_user.email %> (<%= link_to 'Logout', logout_path, method: :delete %>)
<% end %>

<%= yield %>

</body>
</html>

app/views/lti_office365/configure/show.html.erb
<h1>Configure#show</h1>
<p>Find me in app/views/lti_office365/configure/show.html.erb</p>

app/views/lti_office365/files/index.html.erb
<h1><%= link_to 'OneDrive', directory_path %></h1>
<%= link_to 'Back', :back %>
<%= content_tag :ul do -%>
  <% @directory['value'].each do |item| -%>
    <%= content_tag :li do -%>
      <% if item['folder'] -%>
        /<%= link_to item['name'], directory_path(item['id']) %>
      <% else -%>
        <%= link_to item['name'], download_path(item['id']) %>
      <% end -%>
      <%= link_to 'Open in Office365', item['webUrl'], target: '_blank' %>
    <% end -%>
    <!-- <pre><%= JSON.pretty_generate(item) %></pre> -->
  <% end -%>
<% end -%>

app/views/lti_office365/launch/show.html.erb
<h1>Office365</h1>

<% if current_user %>
  <%= link_to 'OneDrive', directory_path %>
  <!-- <%= link_to 'Close', nil, onclick: 'window.close()' %> -->
<% else %>
  <%= link_to 'Sign in with Office365', '/auth/office365', target: '_blank' %>
  <!-- <%= link_to 'Refresh', nil %> -->
<% end %>